# Generated by Django 4.0.5 on 2022-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('released', models.DateField()),
                ('genre', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=128)),
                ('writer', models.CharField(max_length=128)),
                ('actors', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=128)),
                ('awards', models.CharField(max_length=256)),
                ('mox_office', models.FloatField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=128, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=32, null=True)),
                ('runtime', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
